services:
  eta-flow-space:
    image: nodered/node-red:latest
    container_name: eta-flow-space
    ports:
      - "1880:1880"
    volumes:
      - ./flow-space:/data
    restart: unless-stopped
    environment:
      - TZ=Russia/Moscow
    networks:
      - eta-flow-space-network

  eta-flow-space-database:
    image: postgres:latest
    container_name: eta-flow-space-database
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0987654321
      - POSTGRES_DB=eta_flow_space_database
    volumes:
      - ./flow-space-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
        - eta-flow-space-network

networks:
  eta-flow-space-network: